// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_seca_nic

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SecaNicResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"addresses": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"public_ip_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"security_group_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"sku_id": schema.StringAttribute{
				Optional: true,
			},
			"subnet_id": schema.StringAttribute{
				Required: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type SecaNicModel struct {
	Addresses        types.List   `tfsdk:"addresses"`
	Annotations      types.Map    `tfsdk:"annotations"`
	Extensions       types.Map    `tfsdk:"extensions"`
	Labels           types.Map    `tfsdk:"labels"`
	Name             types.String `tfsdk:"name"`
	Provider         types.String `tfsdk:"provider"`
	PublicIpIds      types.List   `tfsdk:"public_ip_ids"`
	SecurityGroupIds types.List   `tfsdk:"security_group_ids"`
	SkuId            types.String `tfsdk:"sku_id"`
	SubnetId         types.String `tfsdk:"subnet_id"`
	Tenant           types.String `tfsdk:"tenant"`
	WorkspaceId      types.String `tfsdk:"workspace_id"`
}
