// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_seca_security_group

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecaSecurityGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"rule_refs": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"rules": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"direction": schema.StringAttribute{
							Computed: true,
						},
						"icmp": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"code": schema.Int64Attribute{
									Computed: true,
								},
								"type": schema.Int64Attribute{
									Computed: true,
								},
							},
							CustomType: IcmpType{
								ObjectType: types.ObjectType{
									AttrTypes: IcmpValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"ports": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"from": schema.Int64Attribute{
									Computed: true,
								},
								"list": schema.ListAttribute{
									ElementType: types.Int64Type,
									Computed:    true,
								},
								"to": schema.Int64Attribute{
									Computed: true,
								},
							},
							CustomType: PortsType{
								ObjectType: types.ObjectType{
									AttrTypes: PortsValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"protocol": schema.StringAttribute{
							Computed: true,
						},
						"source_refs": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"version": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: RulesType{
						ObjectType: types.ObjectType{
							AttrTypes: RulesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"workspace": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type SecaSecurityGroupModel struct {
	Annotations types.Map    `tfsdk:"annotations"`
	Extensions  types.Map    `tfsdk:"extensions"`
	Labels      types.Map    `tfsdk:"labels"`
	Name        types.String `tfsdk:"name"`
	Provider    types.String `tfsdk:"provider"`
	RuleRefs    types.List   `tfsdk:"rule_refs"`
	Rules       types.List   `tfsdk:"rules"`
	State       types.String `tfsdk:"state"`
	Tenant      types.String `tfsdk:"tenant"`
	Workspace   types.String `tfsdk:"workspace"`
	WorkspaceId types.String `tfsdk:"workspace_id"`
}

var _ basetypes.ObjectTypable = RulesType{}

type RulesType struct {
	basetypes.ObjectType
}

func (t RulesType) Equal(o attr.Type) bool {
	other, ok := o.(RulesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RulesType) String() string {
	return "RulesType"
}

func (t RulesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	directionAttribute, ok := attributes["direction"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`direction is missing from object`)

		return nil, diags
	}

	directionVal, ok := directionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`direction expected to be basetypes.StringValue, was: %T`, directionAttribute))
	}

	icmpAttribute, ok := attributes["icmp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icmp is missing from object`)

		return nil, diags
	}

	icmpVal, ok := icmpAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icmp expected to be basetypes.ObjectValue, was: %T`, icmpAttribute))
	}

	portsAttribute, ok := attributes["ports"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ports is missing from object`)

		return nil, diags
	}

	portsVal, ok := portsAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ports expected to be basetypes.ObjectValue, was: %T`, portsAttribute))
	}

	protocolAttribute, ok := attributes["protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol is missing from object`)

		return nil, diags
	}

	protocolVal, ok := protocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol expected to be basetypes.StringValue, was: %T`, protocolAttribute))
	}

	sourceRefsAttribute, ok := attributes["source_refs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_refs is missing from object`)

		return nil, diags
	}

	sourceRefsVal, ok := sourceRefsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_refs expected to be basetypes.ListValue, was: %T`, sourceRefsAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RulesValue{
		Direction:  directionVal,
		Icmp:       icmpVal,
		Ports:      portsVal,
		Protocol:   protocolVal,
		SourceRefs: sourceRefsVal,
		Version:    versionVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewRulesValueNull() RulesValue {
	return RulesValue{
		state: attr.ValueStateNull,
	}
}

func NewRulesValueUnknown() RulesValue {
	return RulesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRulesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RulesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RulesValue Attribute Value",
				"While creating a RulesValue value, a missing attribute value was detected. "+
					"A RulesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RulesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RulesValue Attribute Type",
				"While creating a RulesValue value, an invalid attribute value was detected. "+
					"A RulesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RulesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RulesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RulesValue Attribute Value",
				"While creating a RulesValue value, an extra attribute value was detected. "+
					"A RulesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RulesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRulesValueUnknown(), diags
	}

	directionAttribute, ok := attributes["direction"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`direction is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	directionVal, ok := directionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`direction expected to be basetypes.StringValue, was: %T`, directionAttribute))
	}

	icmpAttribute, ok := attributes["icmp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icmp is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	icmpVal, ok := icmpAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icmp expected to be basetypes.ObjectValue, was: %T`, icmpAttribute))
	}

	portsAttribute, ok := attributes["ports"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ports is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	portsVal, ok := portsAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ports expected to be basetypes.ObjectValue, was: %T`, portsAttribute))
	}

	protocolAttribute, ok := attributes["protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	protocolVal, ok := protocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol expected to be basetypes.StringValue, was: %T`, protocolAttribute))
	}

	sourceRefsAttribute, ok := attributes["source_refs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_refs is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	sourceRefsVal, ok := sourceRefsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_refs expected to be basetypes.ListValue, was: %T`, sourceRefsAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return NewRulesValueUnknown(), diags
	}

	return RulesValue{
		Direction:  directionVal,
		Icmp:       icmpVal,
		Ports:      portsVal,
		Protocol:   protocolVal,
		SourceRefs: sourceRefsVal,
		Version:    versionVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewRulesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RulesValue {
	object, diags := NewRulesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRulesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RulesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRulesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRulesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRulesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRulesValueMust(RulesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RulesType) ValueType(ctx context.Context) attr.Value {
	return RulesValue{}
}

var _ basetypes.ObjectValuable = RulesValue{}

type RulesValue struct {
	Direction  basetypes.StringValue `tfsdk:"direction"`
	Icmp       basetypes.ObjectValue `tfsdk:"icmp"`
	Ports      basetypes.ObjectValue `tfsdk:"ports"`
	Protocol   basetypes.StringValue `tfsdk:"protocol"`
	SourceRefs basetypes.ListValue   `tfsdk:"source_refs"`
	Version    basetypes.StringValue `tfsdk:"version"`
	state      attr.ValueState
}

func (v RulesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["direction"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["icmp"] = basetypes.ObjectType{
		AttrTypes: IcmpValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["ports"] = basetypes.ObjectType{
		AttrTypes: PortsValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["protocol"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["source_refs"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Direction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["direction"] = val

		val, err = v.Icmp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["icmp"] = val

		val, err = v.Ports.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ports"] = val

		val, err = v.Protocol.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["protocol"] = val

		val, err = v.SourceRefs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["source_refs"] = val

		val, err = v.Version.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RulesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RulesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RulesValue) String() string {
	return "RulesValue"
}

func (v RulesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var icmp basetypes.ObjectValue

	if v.Icmp.IsNull() {
		icmp = types.ObjectNull(
			IcmpValue{}.AttributeTypes(ctx),
		)
	}

	if v.Icmp.IsUnknown() {
		icmp = types.ObjectUnknown(
			IcmpValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Icmp.IsNull() && !v.Icmp.IsUnknown() {
		icmp = types.ObjectValueMust(
			IcmpValue{}.AttributeTypes(ctx),
			v.Icmp.Attributes(),
		)
	}

	var ports basetypes.ObjectValue

	if v.Ports.IsNull() {
		ports = types.ObjectNull(
			PortsValue{}.AttributeTypes(ctx),
		)
	}

	if v.Ports.IsUnknown() {
		ports = types.ObjectUnknown(
			PortsValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Ports.IsNull() && !v.Ports.IsUnknown() {
		ports = types.ObjectValueMust(
			PortsValue{}.AttributeTypes(ctx),
			v.Ports.Attributes(),
		)
	}

	var sourceRefsVal basetypes.ListValue
	switch {
	case v.SourceRefs.IsUnknown():
		sourceRefsVal = types.ListUnknown(types.StringType)
	case v.SourceRefs.IsNull():
		sourceRefsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		sourceRefsVal, d = types.ListValue(types.StringType, v.SourceRefs.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"direction": basetypes.StringType{},
			"icmp": basetypes.ObjectType{
				AttrTypes: IcmpValue{}.AttributeTypes(ctx),
			},
			"ports": basetypes.ObjectType{
				AttrTypes: PortsValue{}.AttributeTypes(ctx),
			},
			"protocol": basetypes.StringType{},
			"source_refs": basetypes.ListType{
				ElemType: types.StringType,
			},
			"version": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"direction": basetypes.StringType{},
		"icmp": basetypes.ObjectType{
			AttrTypes: IcmpValue{}.AttributeTypes(ctx),
		},
		"ports": basetypes.ObjectType{
			AttrTypes: PortsValue{}.AttributeTypes(ctx),
		},
		"protocol": basetypes.StringType{},
		"source_refs": basetypes.ListType{
			ElemType: types.StringType,
		},
		"version": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"direction":   v.Direction,
			"icmp":        icmp,
			"ports":       ports,
			"protocol":    v.Protocol,
			"source_refs": sourceRefsVal,
			"version":     v.Version,
		})

	return objVal, diags
}

func (v RulesValue) Equal(o attr.Value) bool {
	other, ok := o.(RulesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Direction.Equal(other.Direction) {
		return false
	}

	if !v.Icmp.Equal(other.Icmp) {
		return false
	}

	if !v.Ports.Equal(other.Ports) {
		return false
	}

	if !v.Protocol.Equal(other.Protocol) {
		return false
	}

	if !v.SourceRefs.Equal(other.SourceRefs) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v RulesValue) Type(ctx context.Context) attr.Type {
	return RulesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RulesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"direction": basetypes.StringType{},
		"icmp": basetypes.ObjectType{
			AttrTypes: IcmpValue{}.AttributeTypes(ctx),
		},
		"ports": basetypes.ObjectType{
			AttrTypes: PortsValue{}.AttributeTypes(ctx),
		},
		"protocol": basetypes.StringType{},
		"source_refs": basetypes.ListType{
			ElemType: types.StringType,
		},
		"version": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = IcmpType{}

type IcmpType struct {
	basetypes.ObjectType
}

func (t IcmpType) Equal(o attr.Type) bool {
	other, ok := o.(IcmpType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IcmpType) String() string {
	return "IcmpType"
}

func (t IcmpType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`)

		return nil, diags
	}

	codeVal, ok := codeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.Int64Value, was: %T`, codeAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.Int64Value, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IcmpValue{
		Code:     codeVal,
		IcmpType: typeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewIcmpValueNull() IcmpValue {
	return IcmpValue{
		state: attr.ValueStateNull,
	}
}

func NewIcmpValueUnknown() IcmpValue {
	return IcmpValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIcmpValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IcmpValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IcmpValue Attribute Value",
				"While creating a IcmpValue value, a missing attribute value was detected. "+
					"A IcmpValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IcmpValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IcmpValue Attribute Type",
				"While creating a IcmpValue value, an invalid attribute value was detected. "+
					"A IcmpValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IcmpValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IcmpValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IcmpValue Attribute Value",
				"While creating a IcmpValue value, an extra attribute value was detected. "+
					"A IcmpValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IcmpValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIcmpValueUnknown(), diags
	}

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`)

		return NewIcmpValueUnknown(), diags
	}

	codeVal, ok := codeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.Int64Value, was: %T`, codeAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewIcmpValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.Int64Value, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewIcmpValueUnknown(), diags
	}

	return IcmpValue{
		Code:     codeVal,
		IcmpType: typeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewIcmpValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IcmpValue {
	object, diags := NewIcmpValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIcmpValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IcmpType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIcmpValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIcmpValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIcmpValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIcmpValueMust(IcmpValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IcmpType) ValueType(ctx context.Context) attr.Value {
	return IcmpValue{}
}

var _ basetypes.ObjectValuable = IcmpValue{}

type IcmpValue struct {
	Code     basetypes.Int64Value `tfsdk:"code"`
	IcmpType basetypes.Int64Value `tfsdk:"type"`
	state    attr.ValueState
}

func (v IcmpValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["code"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Code.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["code"] = val

		val, err = v.IcmpType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IcmpValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IcmpValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IcmpValue) String() string {
	return "IcmpValue"
}

func (v IcmpValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"code": basetypes.Int64Type{},
		"type": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"code": v.Code,
			"type": v.IcmpType,
		})

	return objVal, diags
}

func (v IcmpValue) Equal(o attr.Value) bool {
	other, ok := o.(IcmpValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Code.Equal(other.Code) {
		return false
	}

	if !v.IcmpType.Equal(other.IcmpType) {
		return false
	}

	return true
}

func (v IcmpValue) Type(ctx context.Context) attr.Type {
	return IcmpType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IcmpValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"code": basetypes.Int64Type{},
		"type": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = PortsType{}

type PortsType struct {
	basetypes.ObjectType
}

func (t PortsType) Equal(o attr.Type) bool {
	other, ok := o.(PortsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PortsType) String() string {
	return "PortsType"
}

func (t PortsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	fromAttribute, ok := attributes["from"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`from is missing from object`)

		return nil, diags
	}

	fromVal, ok := fromAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`from expected to be basetypes.Int64Value, was: %T`, fromAttribute))
	}

	listAttribute, ok := attributes["list"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list is missing from object`)

		return nil, diags
	}

	listVal, ok := listAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list expected to be basetypes.ListValue, was: %T`, listAttribute))
	}

	toAttribute, ok := attributes["to"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`to is missing from object`)

		return nil, diags
	}

	toVal, ok := toAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`to expected to be basetypes.Int64Value, was: %T`, toAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PortsValue{
		From:  fromVal,
		List:  listVal,
		To:    toVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewPortsValueNull() PortsValue {
	return PortsValue{
		state: attr.ValueStateNull,
	}
}

func NewPortsValueUnknown() PortsValue {
	return PortsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPortsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PortsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PortsValue Attribute Value",
				"While creating a PortsValue value, a missing attribute value was detected. "+
					"A PortsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PortsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PortsValue Attribute Type",
				"While creating a PortsValue value, an invalid attribute value was detected. "+
					"A PortsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PortsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PortsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PortsValue Attribute Value",
				"While creating a PortsValue value, an extra attribute value was detected. "+
					"A PortsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PortsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPortsValueUnknown(), diags
	}

	fromAttribute, ok := attributes["from"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`from is missing from object`)

		return NewPortsValueUnknown(), diags
	}

	fromVal, ok := fromAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`from expected to be basetypes.Int64Value, was: %T`, fromAttribute))
	}

	listAttribute, ok := attributes["list"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list is missing from object`)

		return NewPortsValueUnknown(), diags
	}

	listVal, ok := listAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list expected to be basetypes.ListValue, was: %T`, listAttribute))
	}

	toAttribute, ok := attributes["to"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`to is missing from object`)

		return NewPortsValueUnknown(), diags
	}

	toVal, ok := toAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`to expected to be basetypes.Int64Value, was: %T`, toAttribute))
	}

	if diags.HasError() {
		return NewPortsValueUnknown(), diags
	}

	return PortsValue{
		From:  fromVal,
		List:  listVal,
		To:    toVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewPortsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PortsValue {
	object, diags := NewPortsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPortsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PortsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPortsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPortsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPortsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPortsValueMust(PortsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PortsType) ValueType(ctx context.Context) attr.Value {
	return PortsValue{}
}

var _ basetypes.ObjectValuable = PortsValue{}

type PortsValue struct {
	From  basetypes.Int64Value `tfsdk:"from"`
	List  basetypes.ListValue  `tfsdk:"list"`
	To    basetypes.Int64Value `tfsdk:"to"`
	state attr.ValueState
}

func (v PortsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["from"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["list"] = basetypes.ListType{
		ElemType: types.Int64Type,
	}.TerraformType(ctx)
	attrTypes["to"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.From.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["from"] = val

		val, err = v.List.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["list"] = val

		val, err = v.To.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["to"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PortsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PortsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PortsValue) String() string {
	return "PortsValue"
}

func (v PortsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var listVal basetypes.ListValue
	switch {
	case v.List.IsUnknown():
		listVal = types.ListUnknown(types.Int64Type)
	case v.List.IsNull():
		listVal = types.ListNull(types.Int64Type)
	default:
		var d diag.Diagnostics
		listVal, d = types.ListValue(types.Int64Type, v.List.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"from": basetypes.Int64Type{},
			"list": basetypes.ListType{
				ElemType: types.Int64Type,
			},
			"to": basetypes.Int64Type{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"from": basetypes.Int64Type{},
		"list": basetypes.ListType{
			ElemType: types.Int64Type,
		},
		"to": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"from": v.From,
			"list": listVal,
			"to":   v.To,
		})

	return objVal, diags
}

func (v PortsValue) Equal(o attr.Value) bool {
	other, ok := o.(PortsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.From.Equal(other.From) {
		return false
	}

	if !v.List.Equal(other.List) {
		return false
	}

	if !v.To.Equal(other.To) {
		return false
	}

	return true
}

func (v PortsValue) Type(ctx context.Context) attr.Type {
	return PortsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PortsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"from": basetypes.Int64Type{},
		"list": basetypes.ListType{
			ElemType: types.Int64Type,
		},
		"to": basetypes.Int64Type{},
	}
}
