// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_seca_subnet

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SecaSubnetResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"cidr": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ipv4": schema.StringAttribute{
						Optional: true,
					},
					"ipv6": schema.StringAttribute{
						Optional: true,
					},
				},
				CustomType: CidrType{
					ObjectType: types.ObjectType{
						AttrTypes: CidrValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"network_id": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"route_table_id": schema.StringAttribute{
				Optional: true,
			},
			"sku_id": schema.StringAttribute{
				Optional: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Required: true,
			},
			"zone": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type SecaSubnetModel struct {
	Annotations  types.Map    `tfsdk:"annotations"`
	Cidr         CidrValue    `tfsdk:"cidr"`
	Extensions   types.Map    `tfsdk:"extensions"`
	Labels       types.Map    `tfsdk:"labels"`
	Name         types.String `tfsdk:"name"`
	NetworkId    types.String `tfsdk:"network_id"`
	Provider     types.String `tfsdk:"provider"`
	RouteTableId types.String `tfsdk:"route_table_id"`
	SkuId        types.String `tfsdk:"sku_id"`
	Tenant       types.String `tfsdk:"tenant"`
	WorkspaceId  types.String `tfsdk:"workspace_id"`
	Zone         types.String `tfsdk:"zone"`
}

var _ basetypes.ObjectTypable = CidrType{}

type CidrType struct {
	basetypes.ObjectType
}

func (t CidrType) Equal(o attr.Type) bool {
	other, ok := o.(CidrType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CidrType) String() string {
	return "CidrType"
}

func (t CidrType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ipv4Attribute, ok := attributes["ipv4"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ipv4 is missing from object`)

		return nil, diags
	}

	ipv4Val, ok := ipv4Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ipv4 expected to be basetypes.StringValue, was: %T`, ipv4Attribute))
	}

	ipv6Attribute, ok := attributes["ipv6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ipv6 is missing from object`)

		return nil, diags
	}

	ipv6Val, ok := ipv6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ipv6 expected to be basetypes.StringValue, was: %T`, ipv6Attribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CidrValue{
		Ipv4:  ipv4Val,
		Ipv6:  ipv6Val,
		state: attr.ValueStateKnown,
	}, diags
}

func NewCidrValueNull() CidrValue {
	return CidrValue{
		state: attr.ValueStateNull,
	}
}

func NewCidrValueUnknown() CidrValue {
	return CidrValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCidrValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CidrValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CidrValue Attribute Value",
				"While creating a CidrValue value, a missing attribute value was detected. "+
					"A CidrValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CidrValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CidrValue Attribute Type",
				"While creating a CidrValue value, an invalid attribute value was detected. "+
					"A CidrValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CidrValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CidrValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CidrValue Attribute Value",
				"While creating a CidrValue value, an extra attribute value was detected. "+
					"A CidrValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CidrValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCidrValueUnknown(), diags
	}

	ipv4Attribute, ok := attributes["ipv4"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ipv4 is missing from object`)

		return NewCidrValueUnknown(), diags
	}

	ipv4Val, ok := ipv4Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ipv4 expected to be basetypes.StringValue, was: %T`, ipv4Attribute))
	}

	ipv6Attribute, ok := attributes["ipv6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ipv6 is missing from object`)

		return NewCidrValueUnknown(), diags
	}

	ipv6Val, ok := ipv6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ipv6 expected to be basetypes.StringValue, was: %T`, ipv6Attribute))
	}

	if diags.HasError() {
		return NewCidrValueUnknown(), diags
	}

	return CidrValue{
		Ipv4:  ipv4Val,
		Ipv6:  ipv6Val,
		state: attr.ValueStateKnown,
	}, diags
}

func NewCidrValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CidrValue {
	object, diags := NewCidrValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCidrValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CidrType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCidrValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCidrValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCidrValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCidrValueMust(CidrValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CidrType) ValueType(ctx context.Context) attr.Value {
	return CidrValue{}
}

var _ basetypes.ObjectValuable = CidrValue{}

type CidrValue struct {
	Ipv4  basetypes.StringValue `tfsdk:"ipv4"`
	Ipv6  basetypes.StringValue `tfsdk:"ipv6"`
	state attr.ValueState
}

func (v CidrValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["ipv4"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ipv6"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Ipv4.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ipv4"] = val

		val, err = v.Ipv6.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ipv6"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CidrValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CidrValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CidrValue) String() string {
	return "CidrValue"
}

func (v CidrValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ipv4": basetypes.StringType{},
		"ipv6": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ipv4": v.Ipv4,
			"ipv6": v.Ipv6,
		})

	return objVal, diags
}

func (v CidrValue) Equal(o attr.Value) bool {
	other, ok := o.(CidrValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Ipv4.Equal(other.Ipv4) {
		return false
	}

	if !v.Ipv6.Equal(other.Ipv6) {
		return false
	}

	return true
}

func (v CidrValue) Type(ctx context.Context) attr.Type {
	return CidrType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CidrValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ipv4": basetypes.StringType{},
		"ipv6": basetypes.StringType{},
	}
}
