// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_seca_public_ip

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecaPublicIpDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"address": schema.StringAttribute{
				Computed: true,
			},
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"attached_to": schema.StringAttribute{
				Computed: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"ip_address": schema.StringAttribute{
				Computed: true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"version": schema.StringAttribute{
				Computed: true,
			},
			"workspace": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type SecaPublicIpModel struct {
	Address     types.String `tfsdk:"address"`
	Annotations types.Map    `tfsdk:"annotations"`
	AttachedTo  types.String `tfsdk:"attached_to"`
	Extensions  types.Map    `tfsdk:"extensions"`
	IpAddress   types.String `tfsdk:"ip_address"`
	Labels      types.Map    `tfsdk:"labels"`
	Name        types.String `tfsdk:"name"`
	Provider    types.String `tfsdk:"provider"`
	State       types.String `tfsdk:"state"`
	Tenant      types.String `tfsdk:"tenant"`
	Version     types.String `tfsdk:"version"`
	Workspace   types.String `tfsdk:"workspace"`
	WorkspaceId types.String `tfsdk:"workspace_id"`
}
