// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_seca_internet_gateway

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecaInternetGatewayDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"egress_only": schema.BoolAttribute{
				Computed: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"workspace": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type SecaInternetGatewayModel struct {
	Annotations types.Map    `tfsdk:"annotations"`
	EgressOnly  types.Bool   `tfsdk:"egress_only"`
	Extensions  types.Map    `tfsdk:"extensions"`
	Labels      types.Map    `tfsdk:"labels"`
	Name        types.String `tfsdk:"name"`
	Provider    types.String `tfsdk:"provider"`
	State       types.String `tfsdk:"state"`
	Tenant      types.String `tfsdk:"tenant"`
	Workspace   types.String `tfsdk:"workspace"`
	WorkspaceId types.String `tfsdk:"workspace_id"`
}
