// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_seca_route_table

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SecaRouteTableResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"network_id": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"routes": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"destination_cidr_block": schema.StringAttribute{
							Required: true,
						},
						"target_id": schema.StringAttribute{
							Required: true,
						},
					},
					CustomType: RoutesType{
						ObjectType: types.ObjectType{
							AttrTypes: RoutesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type SecaRouteTableModel struct {
	Annotations types.Map    `tfsdk:"annotations"`
	Extensions  types.Map    `tfsdk:"extensions"`
	Labels      types.Map    `tfsdk:"labels"`
	Name        types.String `tfsdk:"name"`
	NetworkId   types.String `tfsdk:"network_id"`
	Provider    types.String `tfsdk:"provider"`
	Routes      types.List   `tfsdk:"routes"`
	Tenant      types.String `tfsdk:"tenant"`
	WorkspaceId types.String `tfsdk:"workspace_id"`
}

var _ basetypes.ObjectTypable = RoutesType{}

type RoutesType struct {
	basetypes.ObjectType
}

func (t RoutesType) Equal(o attr.Type) bool {
	other, ok := o.(RoutesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RoutesType) String() string {
	return "RoutesType"
}

func (t RoutesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	destinationCidrBlockAttribute, ok := attributes["destination_cidr_block"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_cidr_block is missing from object`)

		return nil, diags
	}

	destinationCidrBlockVal, ok := destinationCidrBlockAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_cidr_block expected to be basetypes.StringValue, was: %T`, destinationCidrBlockAttribute))
	}

	targetIdAttribute, ok := attributes["target_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`target_id is missing from object`)

		return nil, diags
	}

	targetIdVal, ok := targetIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`target_id expected to be basetypes.StringValue, was: %T`, targetIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RoutesValue{
		DestinationCidrBlock: destinationCidrBlockVal,
		TargetId:             targetIdVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewRoutesValueNull() RoutesValue {
	return RoutesValue{
		state: attr.ValueStateNull,
	}
}

func NewRoutesValueUnknown() RoutesValue {
	return RoutesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRoutesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RoutesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RoutesValue Attribute Value",
				"While creating a RoutesValue value, a missing attribute value was detected. "+
					"A RoutesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RoutesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RoutesValue Attribute Type",
				"While creating a RoutesValue value, an invalid attribute value was detected. "+
					"A RoutesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RoutesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RoutesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RoutesValue Attribute Value",
				"While creating a RoutesValue value, an extra attribute value was detected. "+
					"A RoutesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RoutesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRoutesValueUnknown(), diags
	}

	destinationCidrBlockAttribute, ok := attributes["destination_cidr_block"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_cidr_block is missing from object`)

		return NewRoutesValueUnknown(), diags
	}

	destinationCidrBlockVal, ok := destinationCidrBlockAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_cidr_block expected to be basetypes.StringValue, was: %T`, destinationCidrBlockAttribute))
	}

	targetIdAttribute, ok := attributes["target_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`target_id is missing from object`)

		return NewRoutesValueUnknown(), diags
	}

	targetIdVal, ok := targetIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`target_id expected to be basetypes.StringValue, was: %T`, targetIdAttribute))
	}

	if diags.HasError() {
		return NewRoutesValueUnknown(), diags
	}

	return RoutesValue{
		DestinationCidrBlock: destinationCidrBlockVal,
		TargetId:             targetIdVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewRoutesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RoutesValue {
	object, diags := NewRoutesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRoutesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RoutesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRoutesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRoutesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRoutesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRoutesValueMust(RoutesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RoutesType) ValueType(ctx context.Context) attr.Value {
	return RoutesValue{}
}

var _ basetypes.ObjectValuable = RoutesValue{}

type RoutesValue struct {
	DestinationCidrBlock basetypes.StringValue `tfsdk:"destination_cidr_block"`
	TargetId             basetypes.StringValue `tfsdk:"target_id"`
	state                attr.ValueState
}

func (v RoutesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["destination_cidr_block"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["target_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DestinationCidrBlock.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["destination_cidr_block"] = val

		val, err = v.TargetId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["target_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RoutesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RoutesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RoutesValue) String() string {
	return "RoutesValue"
}

func (v RoutesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"destination_cidr_block": basetypes.StringType{},
		"target_id":              basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"destination_cidr_block": v.DestinationCidrBlock,
			"target_id":              v.TargetId,
		})

	return objVal, diags
}

func (v RoutesValue) Equal(o attr.Value) bool {
	other, ok := o.(RoutesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DestinationCidrBlock.Equal(other.DestinationCidrBlock) {
		return false
	}

	if !v.TargetId.Equal(other.TargetId) {
		return false
	}

	return true
}

func (v RoutesValue) Type(ctx context.Context) attr.Type {
	return RoutesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RoutesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"destination_cidr_block": basetypes.StringType{},
		"target_id":              basetypes.StringType{},
	}
}
