// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_seca_instance

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SecaInstanceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"additional_nic_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"anti_affinity_group": schema.StringAttribute{
				Optional: true,
			},
			"boot_volume": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"device_id": schema.StringAttribute{
						Required: true,
					},
					"type": schema.StringAttribute{
						Optional: true,
					},
				},
				CustomType: BootVolumeType{
					ObjectType: types.ObjectType{
						AttrTypes: BootVolumeValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"data_volumes": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"device_id": schema.StringAttribute{
							Required: true,
						},
						"type": schema.StringAttribute{
							Optional: true,
						},
					},
					CustomType: DataVolumesType{
						ObjectType: types.ObjectType{
							AttrTypes: DataVolumesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"primary_nic_id": schema.StringAttribute{
				Optional: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"security_group_id": schema.StringAttribute{
				Optional: true,
			},
			"sku_id": schema.StringAttribute{
				Required: true,
			},
			"ssh_keys": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"user_data": schema.StringAttribute{
				Optional: true,
			},
			"workspace_id": schema.StringAttribute{
				Required: true,
			},
			"zone": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type SecaInstanceModel struct {
	AdditionalNicIds  types.List      `tfsdk:"additional_nic_ids"`
	Annotations       types.Map       `tfsdk:"annotations"`
	AntiAffinityGroup types.String    `tfsdk:"anti_affinity_group"`
	BootVolume        BootVolumeValue `tfsdk:"boot_volume"`
	DataVolumes       types.List      `tfsdk:"data_volumes"`
	Extensions        types.Map       `tfsdk:"extensions"`
	Labels            types.Map       `tfsdk:"labels"`
	Name              types.String    `tfsdk:"name"`
	PrimaryNicId      types.String    `tfsdk:"primary_nic_id"`
	Provider          types.String    `tfsdk:"provider"`
	SecurityGroupId   types.String    `tfsdk:"security_group_id"`
	SkuId             types.String    `tfsdk:"sku_id"`
	SshKeys           types.List      `tfsdk:"ssh_keys"`
	Tenant            types.String    `tfsdk:"tenant"`
	UserData          types.String    `tfsdk:"user_data"`
	WorkspaceId       types.String    `tfsdk:"workspace_id"`
	Zone              types.String    `tfsdk:"zone"`
}

var _ basetypes.ObjectTypable = BootVolumeType{}

type BootVolumeType struct {
	basetypes.ObjectType
}

func (t BootVolumeType) Equal(o attr.Type) bool {
	other, ok := o.(BootVolumeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BootVolumeType) String() string {
	return "BootVolumeType"
}

func (t BootVolumeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	deviceIdAttribute, ok := attributes["device_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`device_id is missing from object`)

		return nil, diags
	}

	deviceIdVal, ok := deviceIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`device_id expected to be basetypes.StringValue, was: %T`, deviceIdAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BootVolumeValue{
		DeviceId:       deviceIdVal,
		BootVolumeType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewBootVolumeValueNull() BootVolumeValue {
	return BootVolumeValue{
		state: attr.ValueStateNull,
	}
}

func NewBootVolumeValueUnknown() BootVolumeValue {
	return BootVolumeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBootVolumeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BootVolumeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BootVolumeValue Attribute Value",
				"While creating a BootVolumeValue value, a missing attribute value was detected. "+
					"A BootVolumeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BootVolumeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BootVolumeValue Attribute Type",
				"While creating a BootVolumeValue value, an invalid attribute value was detected. "+
					"A BootVolumeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BootVolumeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BootVolumeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BootVolumeValue Attribute Value",
				"While creating a BootVolumeValue value, an extra attribute value was detected. "+
					"A BootVolumeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BootVolumeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBootVolumeValueUnknown(), diags
	}

	deviceIdAttribute, ok := attributes["device_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`device_id is missing from object`)

		return NewBootVolumeValueUnknown(), diags
	}

	deviceIdVal, ok := deviceIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`device_id expected to be basetypes.StringValue, was: %T`, deviceIdAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewBootVolumeValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewBootVolumeValueUnknown(), diags
	}

	return BootVolumeValue{
		DeviceId:       deviceIdVal,
		BootVolumeType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewBootVolumeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BootVolumeValue {
	object, diags := NewBootVolumeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBootVolumeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BootVolumeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBootVolumeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBootVolumeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBootVolumeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBootVolumeValueMust(BootVolumeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BootVolumeType) ValueType(ctx context.Context) attr.Value {
	return BootVolumeValue{}
}

var _ basetypes.ObjectValuable = BootVolumeValue{}

type BootVolumeValue struct {
	DeviceId       basetypes.StringValue `tfsdk:"device_id"`
	BootVolumeType basetypes.StringValue `tfsdk:"type"`
	state          attr.ValueState
}

func (v BootVolumeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["device_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DeviceId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["device_id"] = val

		val, err = v.BootVolumeType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BootVolumeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BootVolumeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BootVolumeValue) String() string {
	return "BootVolumeValue"
}

func (v BootVolumeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"device_id": basetypes.StringType{},
		"type":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"device_id": v.DeviceId,
			"type":      v.BootVolumeType,
		})

	return objVal, diags
}

func (v BootVolumeValue) Equal(o attr.Value) bool {
	other, ok := o.(BootVolumeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DeviceId.Equal(other.DeviceId) {
		return false
	}

	if !v.BootVolumeType.Equal(other.BootVolumeType) {
		return false
	}

	return true
}

func (v BootVolumeValue) Type(ctx context.Context) attr.Type {
	return BootVolumeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BootVolumeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"device_id": basetypes.StringType{},
		"type":      basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DataVolumesType{}

type DataVolumesType struct {
	basetypes.ObjectType
}

func (t DataVolumesType) Equal(o attr.Type) bool {
	other, ok := o.(DataVolumesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataVolumesType) String() string {
	return "DataVolumesType"
}

func (t DataVolumesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	deviceIdAttribute, ok := attributes["device_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`device_id is missing from object`)

		return nil, diags
	}

	deviceIdVal, ok := deviceIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`device_id expected to be basetypes.StringValue, was: %T`, deviceIdAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataVolumesValue{
		DeviceId:        deviceIdVal,
		DataVolumesType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewDataVolumesValueNull() DataVolumesValue {
	return DataVolumesValue{
		state: attr.ValueStateNull,
	}
}

func NewDataVolumesValueUnknown() DataVolumesValue {
	return DataVolumesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataVolumesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataVolumesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataVolumesValue Attribute Value",
				"While creating a DataVolumesValue value, a missing attribute value was detected. "+
					"A DataVolumesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataVolumesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataVolumesValue Attribute Type",
				"While creating a DataVolumesValue value, an invalid attribute value was detected. "+
					"A DataVolumesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataVolumesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataVolumesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataVolumesValue Attribute Value",
				"While creating a DataVolumesValue value, an extra attribute value was detected. "+
					"A DataVolumesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataVolumesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataVolumesValueUnknown(), diags
	}

	deviceIdAttribute, ok := attributes["device_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`device_id is missing from object`)

		return NewDataVolumesValueUnknown(), diags
	}

	deviceIdVal, ok := deviceIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`device_id expected to be basetypes.StringValue, was: %T`, deviceIdAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewDataVolumesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewDataVolumesValueUnknown(), diags
	}

	return DataVolumesValue{
		DeviceId:        deviceIdVal,
		DataVolumesType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewDataVolumesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataVolumesValue {
	object, diags := NewDataVolumesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataVolumesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataVolumesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataVolumesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataVolumesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataVolumesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataVolumesValueMust(DataVolumesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataVolumesType) ValueType(ctx context.Context) attr.Value {
	return DataVolumesValue{}
}

var _ basetypes.ObjectValuable = DataVolumesValue{}

type DataVolumesValue struct {
	DeviceId        basetypes.StringValue `tfsdk:"device_id"`
	DataVolumesType basetypes.StringValue `tfsdk:"type"`
	state           attr.ValueState
}

func (v DataVolumesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["device_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DeviceId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["device_id"] = val

		val, err = v.DataVolumesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataVolumesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataVolumesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataVolumesValue) String() string {
	return "DataVolumesValue"
}

func (v DataVolumesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"device_id": basetypes.StringType{},
		"type":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"device_id": v.DeviceId,
			"type":      v.DataVolumesType,
		})

	return objVal, diags
}

func (v DataVolumesValue) Equal(o attr.Value) bool {
	other, ok := o.(DataVolumesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DeviceId.Equal(other.DeviceId) {
		return false
	}

	if !v.DataVolumesType.Equal(other.DataVolumesType) {
		return false
	}

	return true
}

func (v DataVolumesValue) Type(ctx context.Context) attr.Type {
	return DataVolumesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataVolumesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"device_id": basetypes.StringType{},
		"type":      basetypes.StringType{},
	}
}
