// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_seca_role_assignment

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SecaRoleAssignmentResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"roles": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"scopes": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"regions": schema.ListAttribute{
							ElementType: types.StringType,
							Optional:    true,
						},
						"tenants": schema.ListAttribute{
							ElementType: types.StringType,
							Optional:    true,
						},
						"workspaces": schema.ListAttribute{
							ElementType: types.StringType,
							Optional:    true,
						},
					},
					CustomType: ScopesType{
						ObjectType: types.ObjectType{
							AttrTypes: ScopesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required: true,
			},
			"subs": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SecaRoleAssignmentModel struct {
	Annotations types.Map    `tfsdk:"annotations"`
	Extensions  types.Map    `tfsdk:"extensions"`
	Labels      types.Map    `tfsdk:"labels"`
	Name        types.String `tfsdk:"name"`
	Provider    types.String `tfsdk:"provider"`
	Roles       types.List   `tfsdk:"roles"`
	Scopes      types.List   `tfsdk:"scopes"`
	Subs        types.List   `tfsdk:"subs"`
	Tenant      types.String `tfsdk:"tenant"`
}

var _ basetypes.ObjectTypable = ScopesType{}

type ScopesType struct {
	basetypes.ObjectType
}

func (t ScopesType) Equal(o attr.Type) bool {
	other, ok := o.(ScopesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScopesType) String() string {
	return "ScopesType"
}

func (t ScopesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	regionsAttribute, ok := attributes["regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`regions is missing from object`)

		return nil, diags
	}

	regionsVal, ok := regionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`regions expected to be basetypes.ListValue, was: %T`, regionsAttribute))
	}

	tenantsAttribute, ok := attributes["tenants"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tenants is missing from object`)

		return nil, diags
	}

	tenantsVal, ok := tenantsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tenants expected to be basetypes.ListValue, was: %T`, tenantsAttribute))
	}

	workspacesAttribute, ok := attributes["workspaces"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspaces is missing from object`)

		return nil, diags
	}

	workspacesVal, ok := workspacesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspaces expected to be basetypes.ListValue, was: %T`, workspacesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScopesValue{
		Regions:    regionsVal,
		Tenants:    tenantsVal,
		Workspaces: workspacesVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewScopesValueNull() ScopesValue {
	return ScopesValue{
		state: attr.ValueStateNull,
	}
}

func NewScopesValueUnknown() ScopesValue {
	return ScopesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScopesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScopesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScopesValue Attribute Value",
				"While creating a ScopesValue value, a missing attribute value was detected. "+
					"A ScopesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScopesValue Attribute Type",
				"While creating a ScopesValue value, an invalid attribute value was detected. "+
					"A ScopesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScopesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScopesValue Attribute Value",
				"While creating a ScopesValue value, an extra attribute value was detected. "+
					"A ScopesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScopesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScopesValueUnknown(), diags
	}

	regionsAttribute, ok := attributes["regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`regions is missing from object`)

		return NewScopesValueUnknown(), diags
	}

	regionsVal, ok := regionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`regions expected to be basetypes.ListValue, was: %T`, regionsAttribute))
	}

	tenantsAttribute, ok := attributes["tenants"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tenants is missing from object`)

		return NewScopesValueUnknown(), diags
	}

	tenantsVal, ok := tenantsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tenants expected to be basetypes.ListValue, was: %T`, tenantsAttribute))
	}

	workspacesAttribute, ok := attributes["workspaces"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspaces is missing from object`)

		return NewScopesValueUnknown(), diags
	}

	workspacesVal, ok := workspacesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspaces expected to be basetypes.ListValue, was: %T`, workspacesAttribute))
	}

	if diags.HasError() {
		return NewScopesValueUnknown(), diags
	}

	return ScopesValue{
		Regions:    regionsVal,
		Tenants:    tenantsVal,
		Workspaces: workspacesVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewScopesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScopesValue {
	object, diags := NewScopesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScopesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScopesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScopesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScopesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScopesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScopesValueMust(ScopesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScopesType) ValueType(ctx context.Context) attr.Value {
	return ScopesValue{}
}

var _ basetypes.ObjectValuable = ScopesValue{}

type ScopesValue struct {
	Regions    basetypes.ListValue `tfsdk:"regions"`
	Tenants    basetypes.ListValue `tfsdk:"tenants"`
	Workspaces basetypes.ListValue `tfsdk:"workspaces"`
	state      attr.ValueState
}

func (v ScopesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["regions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["tenants"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["workspaces"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Regions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["regions"] = val

		val, err = v.Tenants.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tenants"] = val

		val, err = v.Workspaces.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["workspaces"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScopesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScopesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScopesValue) String() string {
	return "ScopesValue"
}

func (v ScopesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var regionsVal basetypes.ListValue
	switch {
	case v.Regions.IsUnknown():
		regionsVal = types.ListUnknown(types.StringType)
	case v.Regions.IsNull():
		regionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		regionsVal, d = types.ListValue(types.StringType, v.Regions.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"tenants": basetypes.ListType{
				ElemType: types.StringType,
			},
			"workspaces": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	var tenantsVal basetypes.ListValue
	switch {
	case v.Tenants.IsUnknown():
		tenantsVal = types.ListUnknown(types.StringType)
	case v.Tenants.IsNull():
		tenantsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		tenantsVal, d = types.ListValue(types.StringType, v.Tenants.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"tenants": basetypes.ListType{
				ElemType: types.StringType,
			},
			"workspaces": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	var workspacesVal basetypes.ListValue
	switch {
	case v.Workspaces.IsUnknown():
		workspacesVal = types.ListUnknown(types.StringType)
	case v.Workspaces.IsNull():
		workspacesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		workspacesVal, d = types.ListValue(types.StringType, v.Workspaces.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"tenants": basetypes.ListType{
				ElemType: types.StringType,
			},
			"workspaces": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"regions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"tenants": basetypes.ListType{
			ElemType: types.StringType,
		},
		"workspaces": basetypes.ListType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"regions":    regionsVal,
			"tenants":    tenantsVal,
			"workspaces": workspacesVal,
		})

	return objVal, diags
}

func (v ScopesValue) Equal(o attr.Value) bool {
	other, ok := o.(ScopesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Regions.Equal(other.Regions) {
		return false
	}

	if !v.Tenants.Equal(other.Tenants) {
		return false
	}

	if !v.Workspaces.Equal(other.Workspaces) {
		return false
	}

	return true
}

func (v ScopesValue) Type(ctx context.Context) attr.Type {
	return ScopesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScopesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"regions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"tenants": basetypes.ListType{
			ElemType: types.StringType,
		},
		"workspaces": basetypes.ListType{
			ElemType: types.StringType,
		},
	}
}
