// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_seca_image

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecaImageDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"block_storage_id": schema.StringAttribute{
				Computed: true,
			},
			"boot": schema.StringAttribute{
				Computed: true,
			},
			"cpu_architecture": schema.StringAttribute{
				Computed: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"initializer": schema.StringAttribute{
				Computed: true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"size_mb": schema.Int64Attribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SecaImageModel struct {
	Annotations     types.Map    `tfsdk:"annotations"`
	BlockStorageId  types.String `tfsdk:"block_storage_id"`
	Boot            types.String `tfsdk:"boot"`
	CpuArchitecture types.String `tfsdk:"cpu_architecture"`
	Extensions      types.Map    `tfsdk:"extensions"`
	Initializer     types.String `tfsdk:"initializer"`
	Labels          types.Map    `tfsdk:"labels"`
	Name            types.String `tfsdk:"name"`
	Provider        types.String `tfsdk:"provider"`
	SizeMb          types.Int64  `tfsdk:"size_mb"`
	State           types.String `tfsdk:"state"`
	Tenant          types.String `tfsdk:"tenant"`
}
