// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_seca_image

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SecaImageResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"block_storage_id": schema.StringAttribute{
				Required: true,
			},
			"boot": schema.StringAttribute{
				Optional: true,
			},
			"cpu_architecture": schema.StringAttribute{
				Required: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"initializer": schema.StringAttribute{
				Optional: true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SecaImageModel struct {
	Annotations     types.Map    `tfsdk:"annotations"`
	BlockStorageId  types.String `tfsdk:"block_storage_id"`
	Boot            types.String `tfsdk:"boot"`
	CpuArchitecture types.String `tfsdk:"cpu_architecture"`
	Extensions      types.Map    `tfsdk:"extensions"`
	Initializer     types.String `tfsdk:"initializer"`
	Labels          types.Map    `tfsdk:"labels"`
	Name            types.String `tfsdk:"name"`
	Provider        types.String `tfsdk:"provider"`
	Tenant          types.String `tfsdk:"tenant"`
}
