// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_seca_block_storage

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecaBlockStorageDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"attached_to": schema.StringAttribute{
				Computed: true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"size_gb": schema.Int64Attribute{
				Computed: true,
			},
			"sku_id": schema.StringAttribute{
				Computed: true,
			},
			"source_image_id": schema.StringAttribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"workspace": schema.StringAttribute{
				Computed: true,
			},
			"workspace_id": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type SecaBlockStorageModel struct {
	Annotations   types.Map    `tfsdk:"annotations"`
	AttachedTo    types.String `tfsdk:"attached_to"`
	Extensions    types.Map    `tfsdk:"extensions"`
	Labels        types.Map    `tfsdk:"labels"`
	Name          types.String `tfsdk:"name"`
	Provider      types.String `tfsdk:"provider"`
	SizeGb        types.Int64  `tfsdk:"size_gb"`
	SkuId         types.String `tfsdk:"sku_id"`
	SourceImageId types.String `tfsdk:"source_image_id"`
	State         types.String `tfsdk:"state"`
	Tenant        types.String `tfsdk:"tenant"`
	Workspace     types.String `tfsdk:"workspace"`
	WorkspaceId   types.String `tfsdk:"workspace_id"`
}
