// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_seca_storage_sku

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecaStorageSkuDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"annotations": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"extensions": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"iops": schema.Int64Attribute{
				Computed: true,
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"min_volume_size": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"provider": schema.StringAttribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SecaStorageSkuModel struct {
	Annotations   types.Map    `tfsdk:"annotations"`
	Extensions    types.Map    `tfsdk:"extensions"`
	Iops          types.Int64  `tfsdk:"iops"`
	Labels        types.Map    `tfsdk:"labels"`
	MinVolumeSize types.Int64  `tfsdk:"min_volume_size"`
	Name          types.String `tfsdk:"name"`
	Provider      types.String `tfsdk:"provider"`
	State         types.String `tfsdk:"state"`
	Tenant        types.String `tfsdk:"tenant"`
	Type          types.String `tfsdk:"type"`
}
